spring:
  application:
    name: coruscant
  datasource:
    url: jdbc:postgresql://localhost:5432/coruscant
    username: coruscant
    password: coruscant
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

coruscant:
  security:
    api-keys: []